site_name: Practice Makes Perfect
site_description: Study Notes
site_url: https://practice.eecs.pro

repo_name: eecsmap/practice
repo_url: https://github.com/eecsmap/practice

theme:
  name: material
  language: en
  features:
    - tabs
    - content.code.annotate 

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - Course:
    - ucb.math.1a: 'course/ucb.math.1a/index.md'
  - Log: 'log.md'
  - Algorithms:
    - 'Big O': 'algorithms/asymptotic_analysis.md'
  - Data Structure:
    - 'main': 'data_structure/index.md'
    - 'BST': 'data_structure/bst.md'
    - 'Graph': 'data_structure/graph.md'
    - 'Suffix Array': 'data_structure/sa.md'
  - Java: 'java.md'
  - Probability:
    - 'main': 'probability/index.md'
  - 快速排序: '快速排序.md'
  - 图: '图.md'
  - MIT S6.081: 'mit_6.s081/index.md'
  - hints: 'hint.md'
  - Bayes: 'bayes.md'
  - RSA: 'rsa.md'
  - Verify Cerfiticate: 'certificate_verification.md'
  - books:
    - 'C Interfaces and Implementations': 'books/c_interfaces_and_implementations.md'
  - compiler courses:
    - 'ca.sfu.cmpt379.2022.fall': 'ca.sfu.cmpt379.2022.fall.md'
  - FPGA:
    - 'basic': fpga/basic.md